version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    privileged: true
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
volumes:
  mariadb_data:
